apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2homesteads

commonLabels:
  app.kubernetes.io/part-of: gw2homesteads

resources:
- ../base
- database
- web

images:
- name: ghcr.io/gw2treasures/gw2homesteads.com/web
  newTag: latest

- name: ghcr.io/gw2treasures/gw2homesteads.com/database-migration
  newTag: latest
