apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gw2homesteads

commonLabels:
  app.kubernetes.io/part-of: gw2homesteads

resources:
- namespace.yaml
- database
- database-migration
- web
